### PR TITLE
Run periodic job explicitly

### PR DESCRIPTION
**Pull request by comzeradd**
Every time we deploy the code `schedule` is initialized and we have to wait for another week. It's better to run schedule the jobs explicitly.

### CODE REVIEW

**Comment by comzeradd** [comment]
@johngian r?

**Comment by akatsoulas** [comment]
The only difference with what you are describing is that instead of waiting for the task to re-run for a week, you are waiting timedelta(days=Friday - release date). I would suggest to leave this as is and add a manual trigger through the admin to run the command.

**Comment by johngian** [comment]
+1

It doesn't really tackle the issue here by defining a specific date.

**Comment by comzeradd** [comment]
Agreed. Closing this in favor of #19

**Pull request closed without merging**
