### PR TITLE
Add git to docker

### LINKED ISSUE #10: Dockerfile issue
`git` used in `bin/run-common.sh` but is not available in Dockerfile apt dependencies.

### PR DESCRIPTION
**Pull request by comzeradd**
- Fixes #10

### CODE REVIEW

**Comment by comzeradd** [comment]
@johngian quick r?

**Comment by johngian** [comment]
r+

**Comment by johngian** [comment]
Btw why do you need gettext?

**Comment by comzeradd** [comment]
Thanks. I removed gettext. It's not needed.

**Pull request merged**
