### PR TITLE
Use schedule lib for feching API data

### PR DESCRIPTION
**Pull request by comzeradd**
This replaces celery with the [schedule library](https://github.com/dbader/schedule/).

### CODE REVIEW

**Comment by akatsoulas** [comment]
Nice idea to remove celery for something so simple. That said, why don't you use a management command run by cron? Seems much simpler.

**Comment by comzeradd** [comment]
I have [another branch](https://github.com/comzeradd/cardano/tree/cron) trying the the cron approach, but it seems it's rather difficult and hacky to run a cron service inside a container.

**Comment by johngian** [comment]
Please split this commit to 2. The one removing celery functionality and dependencies and the other one with the new command and the new dependencies.

**Comment by johngian** [comment]
FYI it would be much easier to simply use cron instead of anacron. I don't have any strong opinion though on which one to use.

**Comment by comzeradd** [comment]
PR updated with separated commits.

**Comment by comzeradd** [comment]
PR updated

**Comment by johngian** [comment]
Code looks OK. I haven't tested it locally though.

**Pull request merged**
